Initial commit
AludraTest/aludratest-email pull request #1
Opened 2016-11-15 19:50 UTC by vbergmann

2016-11-16 13:15 UTC, falbrech-hsdg requested changes
Please check comments. Also, a test case should be added which checks that the message text is really attached to the test log. See LoggingFileServiceTest for an example.

2016-11-16 13:15 UTC, falbrech-hsdg commented on src/main/java/org/aludratest/service/smtp/SmtpService.java
> +	@ConfigProperty(name = "sslCheckserveridentity", description = "If set to true, checks the server identity " +
I would prefer full camel case: sslCheckServerIdentity

2016-11-16 13:15 UTC, falbrech-hsdg commented on src/main/java/org/aludratest/service/smtp/impl/SmtpAction.java
> +	private void sendPlainTextMail(String sender, String[] recipients, String subject, @AttachParameter("Message text") String text) {
Are you sure `@AttachParameter` will work here (is required here)?

2016-11-16 13:15 UTC, falbrech-hsdg commented on src/main/java/org/aludratest/service/smtp/impl/SmtpAction.java
> +	private void sendMailWithAttachments(String sender, String[] recipients, String subject, @AttachParameter("Message text") String text,
Same as above

2016-11-16 13:15 UTC, falbrech-hsdg commented on src/main/java/org/aludratest/service/smtp/SmtpInteraction.java
> +			String[] filesToAttach,
Javadoc required: What format shall the String for each file have? Additionally, would be great if they were also attached to the log.

2016-11-16 16:59 UTC, vbergmann commented on src/main/java/org/aludratest/service/smtp/SmtpInteraction.java
> +			String[] filesToAttach,
Good review! I provided the requested changes and added a TODO note that currently the email attachments are not logged.

2016-11-17 08:50 UTC, falbrech-hsdg approved these changes

2016-11-17 08:50 UTC, merged